#!/usr/bin/perl

# Sunclock, draw a clock with local solar and lunar information
# Copyright (C) 2022,2023 Adam Wozniak / GorillaSapiens
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

while (<DATA>) {
   print $_;
}

#=================
# read input

@cont = <>;

#=================
# find markers

$state = 0;
for ($i = 0; $i <= $#cont; $i++) {
   if ($state == 0) {
      if ($cont[$i] =~ /columns rows colors chars-per-pixel/) {
         $state = 1;
         $marker1 = $i;
      }
   }
   elsif ($state == 1) {
      if ($cont[$i] =~ /pixels/) {
         $state = 2;
         $marker2 = $i;
         last;
      }
   }
}

#=================
# parse parameters

$params = $cont[$marker1 + 1];
$params =~ s/[\x0a\x0d,]*$//g;
$params =~ s/[\"]//g;
($columns, $rows, $colors, $chars) = split / /, $params;

print "int columns = $columns;\n";
print "int rows = $rows;\n";
print "int colors = $colors;\n";
print "//int chars = $chars;\n";

#=================
# process /usr/share/X11/rgb.txt

open FILE, "/usr/share/X11/rgb.txt";
while (<FILE>) {
   s/[\x0a\x0d]//g;
   if (!(/^\!/)) {
      s/\t/ /g;
      s/[ ]+/ /g;
      s/^[ ]+//g;
      @all = split / /;
      $r = shift @all;
      $g = shift @all;
      $b = shift @all;
      $name = join(" ", @all);
      $v = ($r << 16) | ($g << 8) | $b;
      $v = sprintf("%06x", $v);
      $rgb_txt{$name} = $v;
   }
}
close FILE;

#=================
# kludge the "None" color
$rgb_txt{"None"} = "ff000000";

#=================
# print palette

print "int palette[$colors] = {\n  ";
for ($i = 0; $i < $colors; $i++) {
   $line = $cont[$marker1 + 2 + $i];
   $line =~ s/[\x0a\x0d,]*$//g;
   $line =~ s/[\"]//g;

   if (!($line =~ / c \#/)) {
      $name = $line;
      $name =~ s/^.* c //g;
      if (defined($rgb_txt{$name})) {
         $v = $rgb_txt{$name};
      }
      else {
         die "Unknown color $name\n";
      }
      $line =~ s/ c $name/ c #$v/g;
   }

   @line = split //, $line;
   while ($#line + 1 != $chars) {
      pop @line;
   }
   $sygil = join "", @line;
   $sygil{$sygil} = $i;

   $line =~ s/^.* c \#//g;

   if (length($line) == 4*3) {
      # srsly who needs that many colors?
      $line =~ s/(..)..(..)..(..)../"$1$2$3"/ge;
   }

   $line = uc($line);

   print " 0x$line";
   if ($i != $colors - 1) {
      print ",";
   }
   if ($i % 4 == 3) {
      print "\n";
   }
   if ($i != $colors - 1) {
      print "  ";
   }
}
if (($colors - 1) % 4 != 3) {
   print "\n";
}
print "};\n";

#=================

print "unsigned char bitmap[$rows][$columns] = {\n";

for ($y = 0; $y < $rows; $y++) {
   $x = 0;
   print "   { ";

   $n = $marker2 + 1 + $y;
   $line = $cont[$n];
   $line =~ s/[\x0a\x0d]//g;
   $line =~ s/^"//g;
   $line =~ s/".*$//g;

   @line = split //, $line;
   $sygil = "";
   while ($#line >= 0) {
      while (length($sygil) != $chars) {
         $sygil .= shift(@line);
      }
      $c = $sygil{$sygil};
      printf(" 0x%02x", $c);
      $x++;
      if ($#line >= 0) {
         print ",";
         if ($x % 8 == 0) {
            print "\n     ";
         }
      }

      $sygil = "";
   }

   print "  }";
   if ($y != $rows - 1) {
      print ",";
   }
   print "\n";
}

print "};\n",

__END__
//  Sunclock, draw a clock with local solar and lunar information
//  Copyright (C) 2022,2023 Adam Wozniak / GorillaSapiens
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.

// This file is autogenerated, changes here will be lost.

